version: '3'
services:
  mortgage:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mortgage-backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/usr/src/app
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./mortgage:/usr/src/app/mortgage
    networks:
      - mortgage_network
    ports:
      - "5005:5005"
    command: python ./mortgage/api_mortgage.py

networks:
  mortgage_network:
    name: mortgage_network

